# Generated by Django 3.0.8 on 2021-06-21 18:36

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import restaurant.models.restaurant


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('updated_by', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('slug', models.CharField(editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(null=True)),
                ('logo', models.TextField(null=True)),
                ('banner', models.TextField(null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('closed', 'closed'), ('suspended', 'suspended'), ('archived', 'archived')], default='inactive', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('delivery_methods', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('office_delivery', 'office_delivery'), ('home_delivery', 'home_delivery'), ('takeaway', 'takeaway'), ('dine_in', 'dine_in')], default=restaurant.models.restaurant.get_default_delivery_method, max_length=100), size=None)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'restaurants',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['name'], name='restaurants_name_cc4837_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['is_active'], name='restaurants_is_acti_05aaa6_idx'),
        ),
    ]
