"""
Django settings for lunch_decision_maker project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
from lunch_decision_maker.settings.settings import *
from lunch_decision_maker.settings.base import *
from lunch_decision_maker.settings.apps import *
from lunch_decision_maker.settings.app_vars import *
from lunch_decision_maker.settings.logger import *
from lunch_decision_maker.settings.database import *
from lunch_decision_maker.settings.third_party import *
from lunch_decision_maker.settings.celery import *
